POST http://localhost:4000/api/registration
Content-Type: application/json

{
    "name": "jack",
    "username": "jack",
    "email": "test@gmail.com",
    "password": "password"
}

###
POST http://localhost:4000/api/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "password"
}